backend:
  name: github
  repo: pc-kirchberg/join2019


media_folder: 'images/'

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: pages/
    extension: .md
    create: true
    format: frontmatter
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}.md"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: body, name: body, widget: markdown}